# Generated by Django 2.1.7 on 2019-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190314_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
