# Generated by Django 2.1.7 on 2019-03-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
