# Generated by Django 2.1.7 on 2019-03-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190321_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Все статьи'},
        ),
    ]
