# Generated by Django 2.1.7 on 2019-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитата на главной странице',
            },
        ),
    ]
