# Generated by Django 2.1.7 on 2019-03-17 08:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('static_elements', '0002_someinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someinfo',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
