# Generated by Django 2.1.7 on 2019-03-14 08:50

import datetime
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mail')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст')),
                ('published', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to=reviews.models.Review.get_picture_url, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Все отзывы',
            },
        ),
    ]
