# Generated by Django 2.1.7 on 2019-03-18 08:29

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190318_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.Review.get_picture_url, verbose_name='Фото'),
        ),
    ]
