# Generated by Django 2.1.7 on 2019-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_strings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailfromstring',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=250, verbose_name='EMAIL_HOST'),
        ),
        migrations.AlterField(
            model_name='mailfromstring',
            name='email_host_password',
            field=models.CharField(default='khysaqitvdnqtneg', max_length=250, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
        migrations.AlterField(
            model_name='mailfromstring',
            name='email_host_user',
            field=models.EmailField(default='goga23d@gmail.com', max_length=250, verbose_name='EMAIL_HOST_USER'),
        ),
    ]
