# Generated by Django 2.1.7 on 2019-03-15 06:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('days_number', models.PositiveSmallIntegerField(default=1, verbose_name='Количество дней')),
                ('hours_number', models.PositiveSmallIntegerField(default=1, verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['date'],
            },
        ),
    ]
