# Generated by Django 2.1.7 on 2019-03-15 08:15

from django.db import migrations, models
import seminars.models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_auto_20190315_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['date'], 'verbose_name': 'Семинар', 'verbose_name_plural': 'Все семинары'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(default=1, upload_to=seminars.models.Seminar.get_picture_url, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
