# Generated by Django 2.1.7 on 2019-03-16 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_auto_20190315_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата завершения')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Ближайший семинар',
                'verbose_name_plural': 'Ближайшие семинары',
                'ordering': ['date_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name': 'Семинар', 'verbose_name_plural': 'Все семинары'},
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.AddField(
            model_name='upcomingseminar',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_seminars', to='seminars.Seminar', verbose_name='Заголовок'),
        ),
    ]
