# Generated by Django 2.1.7 on 2019-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_seminar_in_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='video',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
