# Generated by Django 2.1.7 on 2019-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_auto_20190321_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['my_order'], 'verbose_name': 'Семинар', 'verbose_name_plural': 'Все семинары'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
