# Generated by Django 2.1.7 on 2019-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0008_auto_20190321_1239'),
    ]
    
    def reorder(apps, schema_editor):
        Seminar = apps.get_model("seminars", "Seminar")
        order = 0
        for item in Seminar.objects.all():
            order += 1
            item.my_order = order
            item.save()

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.RunPython(reorder),
    ]